name: Periodic safety check

on:
  schedule:
    - cron: "0 0 1 * *"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/check-safety.yaml"
  push:
    brances:
      - main
    paths:
      - ".github/workflows/check-safety.yaml"

jobs:
  check-code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9.11]
    env:
      WORKDIR: ./
      PIP_VERSION: 21.2.4
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # NOTE: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
      - name: Install poetry
        id: install-poetry
        run: |
          python -m pip install --upgrade pip==${{ env.PIP_VERSION }}
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Set up cache
        id: set-up-cache
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        id: install-dependencies
        working-directory: ${{ env.WORKDIR }}
        run: |
          poetry install

      - name: Check Safety with safety
        id: check-safety-with-safety
        working-directory: ${{ env.WORKDIR }}
        run: |
          make safety-check
